---

- name: mv  zabbix repo
  copy:
    src: zabbix.repo
    dest: /etc/yum.repos.d/zabbix.repo
- name: install zabbix-agent
  yum:
   name: zabbix-agent
   state: latest
- name: create log dir
  file:
    path:  /data/log/zabbix/
    state: directory
    owner: zabbix
    group: zabbix

- name: "move templates to zabbix agentd"
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
- name: start zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
